name: Deploy Web App

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  DeployBicep:
    name: Deploy Bicep
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep file
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_DEPLOY_RG }}
        template: bicep/deploy.bicep
        parameters: bicep/prod.deploy.parameters.json
    
    # Azure logout
    - name: Logout Azure
      run: |
            az logout
      if: always()

  DeployWebApp:
    name: Deploy Web App
    needs: DeployBicep
    runs-on: ubuntu-latest
    defaults: 
      run: 
        working-directory: bryllupsite
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '19'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test:headless

    - name: Build web app
      run: npm run build

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      env: 
        STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
        SOURCE_PATH: ./dist/bryllupsite
      with:
        inlineScript: |
            az storage blob upload-batch --account-name $STORAGE_ACCOUNT_NAME --auth-mode key -d "$web" -s $SOURCE_PATH

    # Azure logout
    - name: Logout Azure
      run: |
            az logout
      if: always()
